### ISSUE TITLE
Swipe Down Dismiss Not Receiving Callbacks From AuthenticationWebViewController

### ISSUE THREAD

**Issue by rinoarmadiaz** [xendit/xendit-sdk-ios-src#28]
Hi Xendit Team,

i found minor issue on AuthenticationWebViewController when we're trying to call 3ds authentification.

so the issue is when we're calling `Xendit.createAuthentication()` for presenting a 3ds webview, we're not getting the error callback when user are trying to dismiss the presented ViewController (AuthenticationWebViewController) which triggered from `@objc func cancelAuthentication() `

i have two suggestion here,

either we disable swipe to dismiss the Presenting ViewController (AuthentificationWebViewController) or we call cancelAuthentification() on viewWillDissapear() so the App will know if the webview is dismissed.

i'm using version:
  - Xendit (3.0.0-beta)

![gif](https://user-images.githubusercontent.com/31609667/102744609-d69c9300-438c-11eb-80d4-1394aa983734.gif)

thanks in advance!

**Comment by sergioutama** [comment]
@rinoarmadiaz does this PR https://github.com/xendit/xendit-sdk-ios-src/pull/29
fix the issue ?

**Comment by rinoarmadiaz** [comment]
presentationControllerDidDismiss() should work, thanks for the fix 👍🏻

**Comment by javiersuweijie** [comment]
#31 & #29 
has been merged
