### ISSUE TITLE
Xcode 12.4: Building for iOS Simulator, but the linked and embedded framework was built for iOS + iOS Simulator

### ISSUE THREAD

**Issue by johnnypramadya** [xendit/xendit-sdk-ios-src#30]
Hi Xendit team

i try to run XenditSample on my Xcode 12.4, Suddenly I have faced this error **Building for iOS Simulator, but the linked and embedded framework was built for iOS + iOS Simulato**r. I already follow solution from [https://exerror.com/xcode-12-3-building-for-ios-simulator-but-the-linked-and-embedded-framework-wa/](url) but still didn't work

**Comment by javiersuweijie** [comment]
Hi @johnnypramadya, we have updated some configuration in the workspace.
Can you pull from master and try running again?

**Comment by johnnypramadya** [comment]
> Hi @johnnypramadya, we have updated some configuration in the workspace.
> Can you pull from master and try running again?

yes, i managed to run, thank you
