### ISSUE TITLE
xendit ios sdk not updated on cocoapod

### ISSUE THREAD

**Issue by reyhanjav** [xendit/xendit-sdk-ios-src#39]
i tried to use USD currency on createAuthentication, but this feature only available on version 3.4.0

on cocoapods.org, xendit version is still on 3.3.0

**Comment by javiersuweijie** [comment]
The latest version is deployed on cocoapods. 
https://github.com/CocoaPods/Specs/tree/master/Specs/f/b/f/Xendit

We updated the version to 3.4.1. Please check and open another issue if you have a problem. Thanks for raising this.
