### ISSUE TITLE
Xendit Token Validation doesn't exit function when error is thrown

### ISSUE THREAD

**Issue by haveeehr** [xendit/xendit-sdk-ios-src#68]
In the file XDTCards.swift 

there is the function createToken, where there is a validation to check whether the card is valid or not. 
When the card is invalid it would throw a XenditError 
However, when we know that the card is invalid why would we still proceed to the API call? which would certainly return API_VALIDATION_ERROR

```        
if let error = validateTokenizationRequest(tokenizationRequest: tokenizationRequest) {
    Log.shared.verbose("\(logPrefix) \(error)")
    completion(nil, error)
}
``` 

I suggest to change the code from 

```        
if let error = validateTokenizationRequest(tokenizationRequest: tokenizationRequest) {
    Log.shared.verbose("\(logPrefix) \(error)")
    completion(nil, error)
    return
}
``` 

For context
When we are usingasync await / withCheckedContinuation, 
It has to return continuation only one time 

```
You must invoke the continuation’s resume method exactly once.
```

If it returns more than once it will shown an error:

```
Fatal error: SWIFT TASK CONTINUATION MISUSE: tried to resume its continuation more than once
```

For reference, changing it to something like the createAuthentication would work better 

```
if publishableKey == nil {
    completion(nil, XenditError(errorCode: "VALIDATION_ERROR", message: "Empty publishable key"))
    return
}
```

What's your take on this?

**Comment by malikghani** [comment]
@glyuck @andysg012 @javiersuweijie 

I apologize for the direct mention. 
I understand if supporting **async/await** may not be your current priority, but could you please take a look at this so we can utilize withCheckedContinuation to use Xendit with async/await.

Thanks.

**Comment by LF-XiaofeiShao** [comment]
Are there any plans to fix this? I think this is logically wrong. We should not continue to perform any subsequent operations after getting an error.

**Comment by LF-XiaofeiShao** [comment]
This problem will cause the user to still perform 3DS verification after seeing the error page. This can cause confusion for users.

**Comment by glyuck** [comment]
I don't even remember working on this SDK. 🤦‍♂️
Created a pull request to fix the issue. Nothing else I can do)

**Comment by LF-XiaofeiShao** [comment]
@glyuck  Thanks, hope it can be merged.
